var eventNames = {
    "raids": "Raids",
    "raids-crotasend": "Crota's End",
    "raids-crotasend-hardmode": "Crota's End - Hard Mode",
    "raids-crotasend-hardmode-fresh": "Crota's End - Hard - Fresh",
    "raids-crotasend-hardmode-abyss": "Crota's End - Hard - Abyss",
    "raids-crotasend-hardmode-bridge": "Crota's End - Hard - Bridge",
    "raids-crotasend-hardmode-thrallway": "Crota's End - Hard - Thrallway",
    "raids-crotasend-hardmode-iryut": "Crota's End - Hard - Ir Yut",
    "raids-crotasend-hardmode-crota": "Crota's End - Hard - Crota",
    "raids-crotasend-normalmode": "Crota's End - Normal Mode",
    "raids-crotasend-normalmode-fresh": "Crota's End - Normal - Fresh",
    "raids-crotasend-normalmode-abyss": "Crota's End - Normal - Abyss",
    "raids-crotasend-normalmode-bridge": "Crota's End - Normal - Bridge",
    "raids-crotasend-normalmode-thrallway": "Crota's End - Normal - Thrallway",
    "raids-crotasend-normalmode-iryut": "Crota's End - Normal - Ir Yut",
    "raids-crotasend-normalmode-crota": "Crota's End - Normal - Crota",
    "raids-crotasend-exploration": "Crota's End - Exploration",
    "raids-crotasend-flawless": "Crota's End - Flawless Raider",
    "raids-vaultofglass": "Vault of Glass",
    "raids-vaultofglass-hardmode": "Vault of Glass - Hard Mode",
    "raids-vaultofglass-hardmode-fresh": "Vault of Glass - Hard - Fresh",
    "raids-vaultofglass-hardmode-confluxes": "Vault of Glass - Hard - Confluxes",
    "raids-vaultofglass-hardmode-oracles": "Vault of Glass - Hard - Oracles",
    "raids-vaultofglass-hardmode-templar": "Vault of Glass - Hard - Templar",
    "raids-vaultofglass-hardmode-gorgonmaze": "Vault of Glass - Hard - Gorgon Maze",
    "raids-vaultofglass-hardmode-gatekeeper": "Vault of Glass - Hard - Gatekeeper",
    "raids-vaultofglass-hardmode-atheon": "Vault of Glass - Hard - Atheon",
    "raids-vaultofglass-normalmode": "Vault of Glass - Normal Mode",
    "raids-vaultofglass-normalmode-fresh": "Vault of Glass - Normal - Fresh",
    "raids-vaultofglass-normalmode-confluxes": "Vault of Glass - Normal - Confluxes",
    "raids-vaultofglass-normalmode-oracles": "Vault of Glass - Normal - Oracles",
    "raids-vaultofglass-normalmode-templar": "Vault of Glass - Normal - Templar",
    "raids-vaultofglass-normalmode-gorgonmaze": "Vault of Glass - Normal - Gorgon Maze",
    "raids-vaultofglass-normalmode-gatekeeper": "Vault of Glass - Normal - Gatekeeper",
    "raids-vaultofglass-normalmode-atheon": "Vault of Glass - Normal - Atheon",
    "raids-vaultofglass-exploration": "Vault of Glass - Exploration",
    "raids-vaultofglass-flawless": "Vault of Glass - Flawless Raider",
    "strikes": "Strikes",
    "strikes-nightfall-weekly": "Weekly Nightfall Strike",
    "strikes-heroic-weekly": "Weekly Heroic Strike",
    "strikes-heroic-weekly-30": "Weekly Heroic Strike - Level 30",
    "strikes-heroic-weekly-28": "Weekly Heroic Strike - Level 28",
    "strikes-heroic-weekly-24": "Weekly Heroic Strike - Level 24",
    "strikes-playlist": "Strike Playlist",
    "strikes-playlist-28": "Strike Playlist - Dragon (28)",
    "strikes-playlist-26": "Strike Playlist - Roc (26)",
    "strikes-playlist-24": "Strike Playlist - Tiger (24)",
    "strikes-playlist-22": "Strike Playlist - Wolf (22)",
    "strikes-playlist-20": "Strike Playlist - Viper (20)",
    "strikes-playlist-18": "Strike Playlist - Eagle (18)",
    "strikes-devilslair": "The Devil's Lair",
    "strikes-summoningpits": "The Summoning Pits",
    "strikes-nexus": "The Nexus",
    "strikes-wintersrun": "Winter's Run",
    "strikes-scerberusvaeiii": "Cerberus Vae III",
    "strikes-dustpalace": "Dust Palace",
    "strikes-undyingmind": "The Undying Mind",
    "strikes-willofcrota": "The Will of Crota",
    "farms": "Farming",
    "farms-exclusionzone": "Exclusion Zone Farm",
    "farms-willofcrota": "Will of Crota Farm",
    "farms-patrol": "Patrol Bounty Farm",
    "bounties": "Bounties",
    "bounties-xyur": "Xyur the Unwed",
    "bounties-urzok": "Urzok the Hated",
    "bounties-queensorder": "Queen's Kill Order",
    "story": "Story",
    "story-heroic-daily": "Daily Heroic Story",
    "story-heroic-daily-30": "Daily Heroic Story - Level 30",
    "story-heroic-daily-28": "Daily Heroic Story - Level 28",
    "story-heroic-daily-24": "Daily Heroic Story - Level 24",
    "story-darkbelow": "Story - The Dark Below",
    "story-earth": "Story - Earth",
    "story-moon": "Story - Moon",
    "story-venus": "Story - Venus",
    "story-mars": "Story - Mars",
    "patrol": "Patrol",
    "patrol-publicevents": "Patrol - Public Events Farm",
    "patrol-earth": "Patrol - Earth",
    "patrol-moon": "Patrol - Moon",
    "patrol-venus": "Patrol - Venus",
    "patrol-mars": "Patrol - Mars",
    "crucible": "Crucible",
    "crucible-trialsoforisis": "Crucible - Trials of Osiris",
    "crucible-ironbanner": "Crucible - Iron Banner",
    "crucible-control": "Crucible - Control",
    "crucible-clash": "Crucible - Clash",
    "crucible-rumble": "Crucible - Rumble",
    "crucible-skirmish": "Crucible - Skirmish",
    "crucible-salvage": "Crucible - Salvage",
    "crucible-combinedarms": "Crucible - Combined Arms",
    "clan-recruitment": "Clan recruitment",
    "other": "Other (explain in notes)"
};
var eventAbbreviations = {
    "raids": "Raids",
    "raids-crotasend": "Crota",
    "raids-crotasend-hardmode": "CE Hard",
    "raids-crotasend-hardmode-fresh": "CE HM Fresh",
    "raids-crotasend-hardmode-abyss": "CE HM Abyss",
    "raids-crotasend-hardmode-bridge": "CE HM Bridge",
    "raids-crotasend-hardmode-thrallway": "CE HM Thrallway",
    "raids-crotasend-hardmode-iryut": "CE HM Ir Yut",
    "raids-crotasend-hardmode-crota": "CE HM Crota",
    "raids-crotasend-normalmode": "CE Normal",
    "raids-crotasend-normalmode-fresh": "CE NM Fresh",
    "raids-crotasend-normalmode-abyss": "CE NM Abyss",
    "raids-crotasend-normalmode-bridge": "CE NM Bridge",
    "raids-crotasend-normalmode-thrallway": "CE NM Thrallway",
    "raids-crotasend-normalmode-iryut": "CE NM Ir Yut",
    "raids-crotasend-normalmode-crota": "CE NM Crota",
    "raids-crotasend-exploration": "CE Explore",
    "raids-crotasend-flawless": "CE Flawless",
    "raids-vaultofglass": "VoG",
    "raids-vaultofglass-hardmode": "VoG Hard",
    "raids-vaultofglass-hardmode-fresh": "VoG HM Fresh",
    "raids-vaultofglass-hardmode-confluxes": "VoG HM Confluxes",
    "raids-vaultofglass-hardmode-oracles": "VoG HM Oracles",
    "raids-vaultofglass-hardmode-templar": "VoG HM Templar",
    "raids-vaultofglass-hardmode-gorgonmaze": "VoG HM Gorgon",
    "raids-vaultofglass-hardmode-gatekeeper": "VoG HM Gatekeeper",
    "raids-vaultofglass-hardmode-atheon": "VoG HM Atheon",
    "raids-vaultofglass-normalmode": "VoG Normal",
    "raids-vaultofglass-normalmode-fresh": "VoG NM Fresh",
    "raids-vaultofglass-normalmode-confluxes": "VoG NM Confluxes",
    "raids-vaultofglass-normalmode-oracles": "VoG NM Oracles",
    "raids-vaultofglass-normalmode-templar": "VoG NM Templar",
    "raids-vaultofglass-normalmode-gorgonmaze": "VoG NM Gorgon",
    "raids-vaultofglass-normalmode-gatekeeper": "VoG NM Gatekeeper",
    "raids-vaultofglass-normalmode-atheon": "VoG NM Atheon",
    "raids-vaultofglass-exploration": "VoG Explore",
    "raids-vaultofglass-flawless": "VoG Flawless",
    "strikes": "Strikes",
    "strikes-nightfall-weekly": "Nightfall",
    "strikes-heroic-weekly": "Heroic Strike",
    "strikes-heroic-weekly-30": "Heroic Strike 30",
    "strikes-heroic-weekly-28": "Heroic Strike 28",
    "strikes-heroic-weekly-24": "Heroic Strike 24",
    "strikes-playlist": "Strike Playlist",
    "strikes-playlist-28": "Dragon Playlist",
    "strikes-playlist-26": "Roc Playlist",
    "strikes-playlist-24": "Tiger Playlist",
    "strikes-playlist-22": "Wolf Playlist",
    "strikes-playlist-20": "Viper Playlist",
    "strikes-playlist-18": "Eagle Playlist",
    "strikes-devilslair": "The Devil's Lair",
    "strikes-summoningpits": "The Summoning Pits",
    "strikes-nexus": "The Nexus",
    "strikes-wintersrun": "Winter's Run",
    "strikes-scerberusvaeiii": "Cerberus Vae III",
    "strikes-dustpalace": "Dust Palace",
    "strikes-undyingmind": "The Undying Mind",
    "strikes-willofcrota": "The Will of Crota",
    "farms": "Farming",
    "farms-exclusionzone": "EZ Farm",
    "farms-willofcrota": "WoC Farm",
    "farms-patrol": "Patrol Farm",
    "bounties": "Bounties",
    "bounties-xyur": "Xyur the Unwed",
    "bounties-urzok": "Urzok the Hated",
    "bounties-queensorder": "Queen's Kill Order",
    "story": "Story",
    "story-heroic-daily": "Heroic Story",
    "story-heroic-daily-30": "Heroic Story 30",
    "story-heroic-daily-28": "Heroic Story 28",
    "story-heroic-daily-24": "Heroic Story 24",
    "story-darkbelow": "TDB Story",
    "story-earth": "Earth Story",
    "story-moon": "Moon Story",
    "story-venus": "Venus Story",
    "story-mars": "Mars Story",
    "patrol": "Patrol",
    "patrol-publicevents": "Public Events",
    "patrol-earth": "Earth Patrol",
    "patrol-moon": "Moon Patrol",
    "patrol-venus": "Venus Patrol",
    "patrol-mars": "Mars Patrol",
    "crucible": "Crucible",
    "crucible-trialsoforisis": "Osiris",
    "crucible-ironbanner": "Iron Banner",
    "crucible-control": "Control",
    "crucible-clash": "Clash",
    "crucible-rumble": "Rumble",
    "crucible-skirmish": "Skirmish",
    "crucible-salvage": "Salvage",
    "crucible-combinedarms": "Combined Arms",
    "clan-recruitment": "Recruiting",
    "other": "Other"
};
var platformNames = {
    "xbox360": "Xbox 360",
    "xbox1": "Xbox One",
    "ps3": "Playstation 3",
    "ps4": "Playstation 4"
};
var platformAbbreviations = {"xbox360": "X360", "xbox1": "X1", "ps3": "PS3", "ps4": "PS4"};
var regionNames = {
    "northamerica": "North America",
    "southamerica": "South America",
    "europe": "Europe",
    "asia": "Asia",
    "australia": "Australia/Oceania",
    "other": "Other"
};
var regionAbbreviations = {
    "northamerica": "NA",
    "southamerica": "SA",
    "europe": "EUR",
    "asia": "Asia",
    "australia": "AUS",
    "other": "Other"
};
var linkSites = [{
    "name": "bungie profile",
    "code": "bungie.net",
    "regex": "^http(?:s)?://(?:www\\.)?bungie\\.net"
}, {
    "name": "dtr profile",
    "code": "destinytracker.com",
    "regex": "^http(?:s)?://destinytracker\\.com"
}, {
    "name": "ddb profile",
    "code": "destinydb.com",
    "regex": "^http(?:s)?://(?:www\\.)?destinydb\\.com"
}, {
    "name": "ds.com profile",
    "code": "destinystatus.com",
    "regex": "^http(?:s)?://(?:www\\.)?destinystatus\\.com"
}];
